# syntax=docker/dockerfile:1

FROM alpine:3.18

ARG SSL_PATH=/etc/ssl/private

RUN apk update && \
    apk --no-cache add nginx \
    npm \
    openssl
    # dumb-init && \

RUN adduser -D ts

RUN openssl genrsa -out ${SSL_PATH}/fresh_pong.key 2048 && \
    openssl req -new -key ${SSL_PATH}/fresh_pong.key -out ${SSL_PATH}/fresh_pong.crt \
    -subj "/C=KR/ST=Seoul/L=Gaepodong/O=42seoul/OU=Cadet/CN=jeseo.42.kr" && \
    openssl x509 -req -days 1000 -in ${SSL_PATH}/fresh_pong.crt -signkey ${SSL_PATH}/fresh_pong.key -out ${SSL_PATH}/fresh_pong.crt && \
    chown -R nginx ${SSL_PATH}

WORKDIR /var/www/html

COPY ./conf/nginx.conf /etc/nginx/nginx.conf
COPY ./conf/default.conf /etc/nginx/http.d/default.conf
COPY ./tools/run.sh /home

RUN chmod 755 /home/run.sh

EXPOSE 80 443

ENTRYPOINT ["/bin/sh", "/home/run.sh"]